version: '3.1'
services:

    mysqldb:
        image: mysql:5.6
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - "${MYSQL_DATA_SRC}:/var/lib/mysql"

    wordpress:
        build:
          context: .
        restart: always
        env_file:
            - ".env"
        environment:
            - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
            - WORDPRESS_DB_HOST=${MYSQL_HOST}
            - WORDPRESS_DB_USER=${MYSQL_USER}
            - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 8080:80
        volumes:
            - "${WORDPRESS_DATA}:/var/www/html"

    Redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        restart: always